### ISSUE TITLE
Found it !!! Hope for Pytorch Implement.

### ISSUE THREAD

**Issue by zyXu1996** [google-research/nested-transformer#1]

**Comment by alexander-soare** [comment]
Keep an eye on this [PR](https://github.com/rwightman/pytorch-image-models/pull/731). Weights for `jx_nest_*` will be uploaded soon.

```
import timm
model = timm.create_model('jx_nest_base', pretrained=True)
```

**Comment by zizhaozhang** [comment]
Thank you @alexander-soare for your work!

**Comment by alexander-soare** [comment]
@zizhaozhang it was a pleasure reading through the paper and code to make it happen. Thank you!

**Comment by zizhaozhang** [comment]
Added pytorch link to the readme.

**Comment by alexander-soare** [comment]
@zizhaozhang I just realised you commented on my yt video. Right? The name was Max so I didn't realise it was you, but same display pic

**Comment by zizhaozhang** [comment]
@alexander-soare Yeah it is me:)
