### ISSUE TITLE
Swin Transformer on CIFAR

### ISSUE THREAD

**Issue by KruC92** [google-research/nested-transformer#4]
Could you please let me know the hyperparameters you used to train Swin Transformer on CIFAR100?

**Comment by zizhaozhang** [comment]
Base lr 5e-4 and scaled by total batch size / 512. Trained on 2 GPUs.
Batch size per device is  64 for swin-s 128 for swin-t, and  32 for swin-b.

**Comment by KruC92** [comment]
Thanks
